version: "3.1"

services:
  db:
    image: postgres
    container_name: password-manager-db
    restart: always
    environment:
      POSTGRES_USER: veli
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pasz
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql
